name: memora
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: 6.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.3.5
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  cached_network_image: ^3.3.1
  http: ^1.2.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_native_splash: ^2.2.16
  cloud_firestore: ^4.15.8
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.6
  device_info: ^2.0.2
  flutter_google_maps_webservices: ^1.1.1
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.0.1
  flutter_osm_plugin: 0.70.4
  shared_preferences: ^2.2.3
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.5+3
  flutter_slidable: ^3.1.0
  flutter_phone_direct_caller: ^2.0.0
  freezed_annotation: ^2.4.1



dependency_overrides:
  meta: ^1.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.2
  build_runner: ^2.4.9

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/model/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
